// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.cd;


/**
 * @see br.gov.mdarte.controleacesso.cd.Perfil
 */
    
public class  PerfilImpl     extends br.gov.mdarte.controleacesso.cd.PerfilAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -8787404696671532060L;
        
    public PerfilImpl()  {
    		
    }

    

















}    
