// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.cd;


/**
 * @see br.gov.mdarte.controleacesso.cd.Sistema
 */
    
public class  SistemaImpl     extends br.gov.mdarte.controleacesso.cd.SistemaAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -5595158590236326717L;
        
    public SistemaImpl()  {
    		
    }

    








}    
