// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.cd;


/**
 * @see br.gov.mdarte.controleacesso.cd.Usuario
 */
    
public class  UsuarioImpl     extends br.gov.mdarte.controleacesso.cd.UsuarioAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -8798643464761788062L;
        
    public UsuarioImpl()  {
    		
    }

    public UsuarioImpl(String login)  {
		setLogin(login);
    }








	public String getNomeIdentificadorMenu() {
		// TODO Auto-generated method stub
		return null;
	}

}    
