// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.cd;

import java.security.NoSuchAlgorithmException;

import br.gov.mdarte.controleacesso.eo.Situacao;
import br.gov.mdarte.controleacesso.util.Util;


/**
 * @see br.gov.mdarte.controleacesso.cd.Usuario
 */
    
public class  UsuarioImpl     extends br.gov.mdarte.controleacesso.cd.UsuarioAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -8798643464761788062L;
    
    public UsuarioImpl() {
    	
    }
        
    public UsuarioImpl(String login, String senha, String email) throws NoSuchAlgorithmException  {
		this.setLogin(login);
		this.setSenha(Util.md5(senha));
		this.setSituacao(Situacao.ATIVO);
		this.setEmail(email);
    }

	@Override
	public String getNomeIdentificadorMenu() {
		// TODO Auto-generated method stub
		return null;
	}
}