// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: Util.vsl in andromda-java-cartridge-coppetec.
//
package br.gov.mdarte.controleacesso.util;

import java.text.SimpleDateFormat;
import java.util.Date;


public class Util extends UtilAbstract{
	
	public static String formatDate(Date date){
		String dateFormatted = new SimpleDateFormat("dd/MM/yyyy").format(date);
		return dateFormatted;
	}
}