// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: Util.vsl in andromda-java-cartridge-coppetec.
//
package br.gov.mdarte.controleacesso.util;

import br.gov.mdarte.controleacesso.util.UtilAbstract;

public class Util extends UtilAbstract{

}
