// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.to;

/**
br/gov/mdarte/controleacesso/to/AcaoTOImpl.java
 * 
 */
public  class AcaoTOImpl extends AcaoTO
{

    private static final long serialVersionUID = -2383995855379693281L;




}