// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.to;

/**
br/gov/mdarte/controleacesso/to/PerfilTOImpl.java
 * 
 */
public  class PerfilTOImpl extends PerfilTO
{

    private static final long serialVersionUID = -8787404696671532060L;




}