// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.to;

/**
br/gov/mdarte/controleacesso/to/SistemaTOImpl.java
 * 
 */
public  class SistemaTOImpl extends SistemaTO
{

    private static final long serialVersionUID = -5595158590236326717L;




}