// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.gov.mdarte.controleacesso.to;

/**
br/gov/mdarte/controleacesso/to/UsuarioTOImpl.java
 * 
 */
public  class UsuarioTOImpl extends UsuarioTO
{

    private static final long serialVersionUID = -8798643464761788062L;




}